INSERT INTO Usuario (Nome, Email, Registro) VALUES ('Maria Sophia Cunha', 'zaparecida@example.com', '2022-12-14');
INSERT INTO Usuario (Nome, Email, Registro) VALUES ('Arthur da Mota', 'cassianootto@example.org', '2024-07-13');
INSERT INTO Usuario (Nome, Email, Registro) VALUES ('Bella das Neves', 'bernardo14@example.net', '2021-12-31');
INSERT INTO Usuario (Nome, Email, Registro) VALUES ('Bryan Sampaio', 'vitor21@example.com', '2020-11-26');
INSERT INTO Usuario (Nome, Email, Registro) VALUES ('Valentim Cirino', 'lucas62@example.org', '2019-11-24');
INSERT INTO Usuario (Nome, Email, Registro) VALUES ('Murilo Carvalho', 'zcavalcanti@example.com', '2023-05-03');
INSERT INTO Usuario (Nome, Email, Registro) VALUES ('Henry Gabriel das Neves', 'henrynovaes@example.org', '2023-12-28');
INSERT INTO Usuario (Nome, Email, Registro) VALUES ('Dra. Emilly Abreu', 'pimentaana-luiza@example.org', '2022-03-16');
INSERT INTO Usuario (Nome, Email, Registro) VALUES ('Laís Cardoso', 'montenegrobryan@example.com', '2022-11-04');
INSERT INTO Usuario (Nome, Email, Registro) VALUES ('Marina da Costa', 'davi-luizrocha@example.com', '2022-05-06');
INSERT INTO Usuario (Nome, Email, Registro) VALUES ('Sr. João Cavalcante', 'maria-luiza66@example.com', '2019-12-16');
INSERT INTO Usuario (Nome, Email, Registro) VALUES ('Maria Helena Albuquerque', 'gaelsilva@example.org', '2019-11-08');
INSERT INTO Usuario (Nome, Email, Registro) VALUES ('Ana Luiza Câmara', 'marinamelo@example.org', '2021-08-25');
INSERT INTO Usuario (Nome, Email, Registro) VALUES ('Carlos Eduardo Dias', 'da-luzmarcela@example.org', '2020-09-21');
INSERT INTO Usuario (Nome, Email, Registro) VALUES ('Sra. Emanuelly Moreira', 'aragaoarthur-gabriel@example.com', '2024-10-02');
INSERT INTO Usuario (Nome, Email, Registro) VALUES ('Luiz Felipe das Neves', 'sousahenry@example.net', '2024-01-21');
INSERT INTO Usuario (Nome, Email, Registro) VALUES ('Srta. Yasmin da Cruz', 'cmoura@example.com', '2022-10-05');
INSERT INTO Usuario (Nome, Email, Registro) VALUES ('Sara da Cruz', 'casa-grandedavi-luiz@example.com', '2023-09-22');
INSERT INTO Usuario (Nome, Email, Registro) VALUES ('Yuri Santos', 'lorena63@example.org', '2019-11-19');
INSERT INTO Usuario (Nome, Email, Registro) VALUES ('Luiz Gustavo Leão', 'da-motathiago@example.com', '2020-03-04');

INSERT INTO Artista (Nome, Nascimento) VALUES ('Ana Júlia Freitas', '1974-07-17');
INSERT INTO Artista (Nome, Nascimento) VALUES ('Murilo Câmara', '1993-12-22');
INSERT INTO Artista (Nome, Nascimento) VALUES ('Bernardo Casa Grande', '2001-07-14');
INSERT INTO Artista (Nome, Nascimento) VALUES ('Melissa Moraes', '2000-12-30');
INSERT INTO Artista (Nome, Nascimento) VALUES ('Diogo Campos', '1999-07-15');
INSERT INTO Artista (Nome, Nascimento) VALUES ('Vitor Gabriel Casa Grande', '1981-02-21');
INSERT INTO Artista (Nome, Nascimento) VALUES ('Maria Vitória Caldeira', '1986-07-01');
INSERT INTO Artista (Nome, Nascimento) VALUES ('Sr. Vicente Fogaça', '1972-05-16');
INSERT INTO Artista (Nome, Nascimento) VALUES ('Dra. Emanuella Pinto', '1970-05-22');
INSERT INTO Artista (Nome, Nascimento) VALUES ('Maria Eduarda Aparecida', '1981-04-09');

INSERT INTO Disco (Titulo, Lancamento, ID_Ar) VALUES ('Consequuntur.', '2017-06-17', 8);
INSERT INTO Disco (Titulo, Lancamento, ID_Ar) VALUES ('Quia cumque adipisci.', '2022-12-10', 5);
INSERT INTO Disco (Titulo, Lancamento, ID_Ar) VALUES ('Molestiae perspiciatis esse.', '2017-06-30', 1);
INSERT INTO Disco (Titulo, Lancamento, ID_Ar) VALUES ('Ratione laborum nihil.', '2022-10-04', 1);
INSERT INTO Disco (Titulo, Lancamento, ID_Ar) VALUES ('Dolor occaecati ullam rerum.', '2019-11-24', 1);
INSERT INTO Disco (Titulo, Lancamento, ID_Ar) VALUES ('Odit fugiat debitis.', '2015-11-20', 6);
INSERT INTO Disco (Titulo, Lancamento, ID_Ar) VALUES ('Velit totam repellat.', '2016-09-30', 5);
INSERT INTO Disco (Titulo, Lancamento, ID_Ar) VALUES ('Ex error.', '2023-02-27', 5);
INSERT INTO Disco (Titulo, Lancamento, ID_Ar) VALUES ('Commodi veritatis.', '2021-10-14', 1);
INSERT INTO Disco (Titulo, Lancamento, ID_Ar) VALUES ('Dignissimos pariatur.', '2015-01-02', 2);
INSERT INTO Disco (Titulo, Lancamento, ID_Ar) VALUES ('Dolor eveniet ad.', '2015-07-24', 9);
INSERT INTO Disco (Titulo, Lancamento, ID_Ar) VALUES ('Aliquam explicabo voluptatum.', '2017-05-16', 5);
INSERT INTO Disco (Titulo, Lancamento, ID_Ar) VALUES ('Harum recusandae vero dolore.', '2018-02-19', 10);
INSERT INTO Disco (Titulo, Lancamento, ID_Ar) VALUES ('Cum repudiandae optio.', '2021-08-16', 6);
INSERT INTO Disco (Titulo, Lancamento, ID_Ar) VALUES ('Repellat ullam nisi.', '2019-04-27', 9);
INSERT INTO Disco (Titulo, Lancamento, ID_Ar) VALUES ('Dolor delectus.', '2018-08-05', 4);
INSERT INTO Disco (Titulo, Lancamento, ID_Ar) VALUES ('Ipsa voluptatem recusandae occaecati.', '2020-12-28', 3);
INSERT INTO Disco (Titulo, Lancamento, ID_Ar) VALUES ('Consectetur minima officiis.', '2019-04-17', 4);
INSERT INTO Disco (Titulo, Lancamento, ID_Ar) VALUES ('Labore.', '2019-07-30', 7);
INSERT INTO Disco (Titulo, Lancamento, ID_Ar) VALUES ('Quidem omnis.', '2016-08-26', 9);
INSERT INTO Disco (Titulo, Lancamento, ID_Ar) VALUES ('Praesentium facere.', '2023-07-09', 1);
INSERT INTO Disco (Titulo, Lancamento, ID_Ar) VALUES ('Nulla.', '2016-08-13', 6);
INSERT INTO Disco (Titulo, Lancamento, ID_Ar) VALUES ('Quibusdam soluta iusto voluptatem.', '2022-06-04', 2);
INSERT INTO Disco (Titulo, Lancamento, ID_Ar) VALUES ('Quasi assumenda ea.', '2016-01-17', 3);
INSERT INTO Disco (Titulo, Lancamento, ID_Ar) VALUES ('Sint.', '2022-05-03', 8);
INSERT INTO Disco (Titulo, Lancamento, ID_Ar) VALUES ('Error itaque.', '2019-05-02', 4);
INSERT INTO Disco (Titulo, Lancamento, ID_Ar) VALUES ('Quisquam doloribus eligendi.', '2017-05-14', 1);
INSERT INTO Disco (Titulo, Lancamento, ID_Ar) VALUES ('Harum velit iure.', '2015-10-14', 2);
INSERT INTO Disco (Titulo, Lancamento, ID_Ar) VALUES ('Recusandae qui.', '2021-02-07', 6);
INSERT INTO Disco (Titulo, Lancamento, ID_Ar) VALUES ('Reprehenderit at.', '2023-02-01', 10);

INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Hic dolor.', 251, 29);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Adipisci perferendis voluptatem.', 297, 24);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Consectetur repellat numquam veniam.', 192, 12);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Ullam mollitia soluta sint corporis.', 281, 9);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Neque eligendi amet eligendi.', 253, 17);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Ratione unde at laudantium quos.', 293, 10);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Mollitia esse cupiditate velit.', 251, 19);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Tenetur eos ut.', 242, 4);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Corrupti eos.', 221, 10);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Expedita porro necessitatibus eveniet.', 261, 16);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Maxime maxime esse.', 203, 7);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Officiis quidem.', 200, 21);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Error mollitia numquam.', 276, 25);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Expedita omnis.', 231, 12);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Doloremque quasi id.', 247, 13);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Doloremque sapiente in corrupti quia.', 261, 26);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Quia sed est quaerat.', 245, 14);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Temporibus vitae id.', 198, 9);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Officiis tempore ipsa inventore nobis.', 185, 14);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Saepe corrupti quae minus placeat.', 202, 8);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Quaerat repellendus.', 259, 23);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Quisquam expedita a consectetur ipsa.', 242, 20);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Cum autem.', 272, 29);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Debitis temporibus accusantium.', 184, 15);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Quis aut odit ut.', 275, 15);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Officiis quam magnam nobis illum.', 187, 27);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Ipsam odio.', 242, 10);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Enim accusamus consequuntur tempora exercitationem.', 237, 25);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Quisquam ad autem.', 181, 18);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Assumenda inventore commodi ipsum sit.', 286, 3);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Perspiciatis nulla vel numquam quasi.', 239, 21);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Quas quos perspiciatis assumenda.', 257, 1);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Magnam similique corrupti harum sit.', 232, 16);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Accusantium voluptatem odit.', 299, 21);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Nemo quidem.', 273, 18);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Alias vitae minus molestias ipsa.', 245, 10);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Natus libero sint explicabo.', 254, 20);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Ducimus minus molestias.', 285, 20);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Magnam corporis.', 189, 4);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Illo itaque nobis delectus.', 204, 27);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Blanditiis quam eaque quia.', 193, 19);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Ab velit ratione voluptatem.', 182, 18);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Tempora assumenda accusamus.', 288, 20);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Nemo iure vero.', 251, 26);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Quod consequatur ipsam aliquam.', 208, 15);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Sunt itaque expedita.', 224, 12);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Quia et.', 217, 1);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Distinctio recusandae fugit sunt omnis.', 253, 4);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Earum quo aut.', 279, 18);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Nulla sequi modi laboriosam.', 271, 10);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Deleniti nam officia.', 247, 5);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Delectus porro nobis sint maiores.', 226, 18);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Voluptate iusto odio quos soluta.', 291, 26);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Eligendi eaque repellat molestias.', 274, 21);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Natus dolorem laudantium.', 236, 18);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Rerum odio harum perferendis.', 190, 4);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Voluptate eum tempore vero nostrum.', 292, 26);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Doloremque recusandae veniam suscipit.', 208, 22);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Veritatis architecto quos.', 242, 9);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Aliquam minima velit architecto.', 250, 7);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Placeat temporibus molestias error.', 230, 28);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Iure qui libero consectetur.', 260, 13);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Minima quam sint recusandae.', 187, 20);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Cumque amet quaerat ex ipsam.', 196, 15);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Iusto iste quidem neque maxime.', 209, 12);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Dolor eveniet magnam accusantium.', 202, 7);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Expedita quasi aut.', 207, 11);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Quas facere.', 256, 17);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Earum eveniet tempora iure perferendis.', 285, 5);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Similique totam.', 289, 30);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Corporis impedit eaque.', 267, 23);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Perspiciatis earum ex recusandae.', 260, 13);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Possimus illum quia odio exercitationem.', 255, 11);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Aliquam dolores excepturi sunt delectus.', 242, 24);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Ab assumenda dolorem odit.', 190, 26);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Iste soluta odit.', 253, 8);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Delectus at nihil provident.', 234, 3);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Asperiores nobis ut inventore.', 197, 1);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Aspernatur alias architecto assumenda.', 235, 11);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Temporibus explicabo aperiam.', 247, 17);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Vero laudantium natus deserunt.', 187, 2);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Vero dolorem.', 210, 22);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Reiciendis eaque quae non expedita.', 236, 29);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Laboriosam pariatur nihil.', 209, 14);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Minus ipsa amet recusandae.', 218, 30);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Doloribus doloribus dolore fugit a.', 227, 7);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Placeat molestias facilis at.', 243, 6);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Minima natus exercitationem.', 227, 21);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Officiis sapiente quisquam soluta minima.', 215, 23);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Recusandae vitae temporibus.', 281, 2);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Suscipit sit.', 274, 2);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Necessitatibus nemo nulla libero optio.', 193, 8);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Non exercitationem totam labore asperiores.', 290, 17);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Ducimus commodi facilis.', 296, 23);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Quae magni sint.', 274, 18);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Dolorem sint.', 270, 29);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Illum maxime quae facere quisquam.', 254, 20);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Voluptatum quaerat dignissimos similique.', 276, 23);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Modi aliquam iusto.', 242, 23);
INSERT INTO Musica (Titulo, Duracao, ID_Di) VALUES ('Commodi perferendis praesentium enim nesciunt.', 260, 8);

INSERT INTO Playlist (Titulo, ID_Us) VALUES ('Culpa corrupti.', 19);
INSERT INTO Playlist (Titulo, ID_Us) VALUES ('Quis facilis soluta.', 10);
INSERT INTO Playlist (Titulo, ID_Us) VALUES ('Sequi accusantium.', 19);
INSERT INTO Playlist (Titulo, ID_Us) VALUES ('Aliquid aperiam.', 8);
INSERT INTO Playlist (Titulo, ID_Us) VALUES ('Doloremque officiis autem.', 7);
INSERT INTO Playlist (Titulo, ID_Us) VALUES ('Quaerat aliquam.', 3);
INSERT INTO Playlist (Titulo, ID_Us) VALUES ('Omnis deleniti.', 12);
INSERT INTO Playlist (Titulo, ID_Us) VALUES ('Voluptate.', 7);
INSERT INTO Playlist (Titulo, ID_Us) VALUES ('Quis rem.', 8);
INSERT INTO Playlist (Titulo, ID_Us) VALUES ('Sed consectetur voluptatibus.', 19);
INSERT INTO Playlist (Titulo, ID_Us) VALUES ('Ipsam.', 1);
INSERT INTO Playlist (Titulo, ID_Us) VALUES ('Necessitatibus molestiae corporis.', 1);
INSERT INTO Playlist (Titulo, ID_Us) VALUES ('Dolorem dolores.', 2);
INSERT INTO Playlist (Titulo, ID_Us) VALUES ('Accusantium.', 7);
INSERT INTO Playlist (Titulo, ID_Us) VALUES ('Sit consectetur corrupti.', 8);

INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (74, 5);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (1, 6);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (97, 10);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (20, 7);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (68, 5);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (3, 5);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (50, 1);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (70, 8);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (25, 6);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (56, 10);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (14, 2);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (13, 1);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (68, 9);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (56, 8);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (48, 3);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (88, 8);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (40, 5);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (8, 4);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (69, 2);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (67, 8);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (45, 4);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (32, 1);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (85, 3);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (65, 6);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (96, 8);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (77, 5);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (3, 1);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (87, 8);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (69, 9);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (15, 10);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (25, 6);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (66, 5);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (84, 7);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (39, 7);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (18, 3);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (43, 5);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (23, 3);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (72, 3);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (8, 6);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (12, 6);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (55, 4);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (12, 8);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (74, 8);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (65, 3);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (73, 6);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (79, 4);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (40, 6);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (34, 6);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (8, 10);
INSERT INTO Musica_Artista (ID_Mu, ID_Ar) VALUES (18, 7);

INSERT INTO Playlist_Musica (ID_Pl, ID_Mu) VALUES (10, 53);
INSERT INTO Playlist_Musica (ID_Pl, ID_Mu) VALUES (6, 52);
INSERT INTO Playlist_Musica (ID_Pl, ID_Mu) VALUES (7, 24);
INSERT INTO Playlist_Musica (ID_Pl, ID_Mu) VALUES (9, 27);
INSERT INTO Playlist_Musica (ID_Pl, ID_Mu) VALUES (14, 71);
INSERT INTO Playlist_Musica (ID_Pl, ID_Mu) VALUES (6, 10);
INSERT INTO Playlist_Musica (ID_Pl, ID_Mu) VALUES (10, 16);
INSERT INTO Playlist_Musica (ID_Pl, ID_Mu) VALUES (1, 20);
INSERT INTO Playlist_Musica (ID_Pl, ID_Mu) VALUES (8, 76);
INSERT INTO Playlist_Musica (ID_Pl, ID_Mu) VALUES (4, 28);
INSERT INTO Playlist_Musica (ID_Pl, ID_Mu) VALUES (11, 37);
INSERT INTO Playlist_Musica (ID_Pl, ID_Mu) VALUES (1, 13);
INSERT INTO Playlist_Musica (ID_Pl, ID_Mu) VALUES (10, 29);
INSERT INTO Playlist_Musica (ID_Pl, ID_Mu) VALUES (4, 25);
INSERT INTO Playlist_Musica (ID_Pl, ID_Mu) VALUES (4, 59);
INSERT INTO Playlist_Musica (ID_Pl, ID_Mu) VALUES (13, 75);
INSERT INTO Playlist_Musica (ID_Pl, ID_Mu) VALUES (11, 36);
INSERT INTO Playlist_Musica (ID_Pl, ID_Mu) VALUES (2, 6);
INSERT INTO Playlist_Musica (ID_Pl, ID_Mu) VALUES (10, 10);
INSERT INTO Playlist_Musica (ID_Pl, ID_Mu) VALUES (12, 87);
INSERT INTO Playlist_Musica (ID_Pl, ID_Mu) VALUES (2, 57);
INSERT INTO Playlist_Musica (ID_Pl, ID_Mu) VALUES (1, 97);
INSERT INTO Playlist_Musica (ID_Pl, ID_Mu) VALUES (11, 10);
INSERT INTO Playlist_Musica (ID_Pl, ID_Mu) VALUES (13, 64);
INSERT INTO Playlist_Musica (ID_Pl, ID_Mu) VALUES (3, 19);
INSERT INTO Playlist_Musica (ID_Pl, ID_Mu) VALUES (8, 16);
INSERT INTO Playlist_Musica (ID_Pl, ID_Mu) VALUES (13, 52);
INSERT INTO Playlist_Musica (ID_Pl, ID_Mu) VALUES (8, 17);
INSERT INTO Playlist_Musica (ID_Pl, ID_Mu) VALUES (11, 34);
INSERT INTO Playlist_Musica (ID_Pl, ID_Mu) VALUES (3, 13);
INSERT INTO Playlist_Musica (ID_Pl, ID_Mu) VALUES (10, 50);
INSERT INTO Playlist_Musica (ID_Pl, ID_Mu) VALUES (5, 93);
INSERT INTO Playlist_Musica (ID_Pl, ID_Mu) VALUES (6, 89);
INSERT INTO Playlist_Musica (ID_Pl, ID_Mu) VALUES (7, 56);
INSERT INTO Playlist_Musica (ID_Pl, ID_Mu) VALUES (5, 31);
INSERT INTO Playlist_Musica (ID_Pl, ID_Mu) VALUES (3, 7);
INSERT INTO Playlist_Musica (ID_Pl, ID_Mu) VALUES (13, 33);
INSERT INTO Playlist_Musica (ID_Pl, ID_Mu) VALUES (4, 35);
INSERT INTO Playlist_Musica (ID_Pl, ID_Mu) VALUES (9, 72);
INSERT INTO Playlist_Musica (ID_Pl, ID_Mu) VALUES (12, 59);
